### ISSUE TITLE
Define permissions for disk-encryption-sets too / details on NSGs

### ISSUE THREAD

**Issue by davidkarlsen** [rh-mobb/terraform-aro-permissions#5]
When using disk encryption sets, the ARO RP SP needs Read on the disk-encryption-set.
Also - the documented permissions for NSGs - when I attempt an install with NSGs, this fails with:
```shell
│ Resource Group Name: "tfex-rg-min-aro-uv2b"
│ Open Shift Cluster Name: "tfex-prov-min-aro-uv2b"): polling after CreateOrUpdate: polling failed: the Azure API returned the following error:
│ 
│ Status: "Failed"
│ Code: "InvalidLinkedVNet"
│ Message: "The provided subnet '/subscriptions/xxx/resourceGroups/tfex-rg-min-aro-uv2b/providers/Microsoft.Network/virtualNetworks/tfex-vnet-min-aro-uv2b/subnets/aro-dev1-master' is invalid: must not have a network security group attached."
│ Activity Id: ""
```
are NSGs really supported at all?

I also noticed:
https://github.com/Azure/OpenShift/issues/297
which seems to hint about this being a future feature.

Or maybe NSGs are supported in `UserDefinedRouting` mode and not in `Loadbalancer` mode?

**Comment by scottd018** [comment]
Sorry @davidkarlsen , just now seeing this (for some reason I wasn't notified).  NSGs are recently just supported (see https://learn.microsoft.com/en-us/azure/openshift/howto-bring-nsg).  I believe the NSG piece will work now.  Good call on the disk encryption set.  I am fixing that now.
